apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/sound-chimera-457618-d7/locations/europe-west1-c/clusters/cluster-2
